cjoc:
  image: cloudbees/jenkins-operation-center
  ports:
    - "8080:8080"
    - "50000:50000"
cje01:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8081:8080"
cje02:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8082:8080"
elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
  expose:
    - "9200:9200"
kibana:
  image: kibana:4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
