joc:
  image: cloudbees/jenkins-operation-center
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - ./cjoc_home:/usr/share/jenkins/ref
master01:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8081:8080"
master02:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8082:8080"

