joc:
  image: cloudbees/jenkins-operation-center
  ports:
    - "8080:8080"
    - "50000:50000"
ops-jenkins:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8081:8080"

qa-jenkins:
  image: cloudbees/jenkins-enterprise
  ports:
    - "8082:8080"

